add axum-spa example
pyrossh/rust-embed pull request #184
Opened 2022-08-24 11:58 UTC by frederikhors

I hope this example can be added.

I will also ask axum the same thing.

Thanks for your help.

2022-08-26 03:27 UTC, AzureMarker requested changes
It looks pretty good! Just need to fix up the file organization, and I have a few nits.

2022-08-26 03:27 UTC, AzureMarker commented on examples/axum-spa/Cargo.toml
> +[package]
This example should follow the multi-file example layout specified here:
https://doc.rust-lang.org/cargo/guide/project-layout.html

Basically, it doesn't need a Cargo.toml, just the Rust source files. This also lets it attach to the rest of the workspace and use the common `target` folder.

After this you can delete the .gitignore file.

2022-08-26 03:27 UTC, AzureMarker commented on examples/axum-spa/src/main.rs
> +use mime_guess;
This import is redundant.

2022-08-26 03:27 UTC, AzureMarker commented on examples/axum-spa/src/main.rs
> +    let path = uri.path().trim_start_matches('/').to_string();
nit: The `to_string` is unnecessary.

2022-08-26 03:27 UTC, AzureMarker commented on examples/axum-spa/src/main.rs
> +async fn static_handler(uri: Uri) -> impl IntoResponse {
nit: All of the return types are `Response`, so you could simplify the return type here.

2022-08-26 08:44 UTC, frederikhors commented on examples/axum-spa/src/main.rs
> +async fn static_handler(uri: Uri) -> impl IntoResponse {
Can you please explain it better? I'm new to Rust. What do you mean?

2022-08-26 08:44 UTC, frederikhors commented on examples/axum-spa/src/main.rs
> +    let path = uri.path().trim_start_matches('/').to_string();
Done.

2022-08-26 08:46 UTC, frederikhors commented on examples/axum-spa/Cargo.toml
> +[package]
Done.

2022-08-27 22:20 UTC, AzureMarker commented on examples/axum-spa/src/main.rs
> +async fn static_handler(uri: Uri) -> impl IntoResponse {
```suggestion
async fn static_handler(uri: Uri) -> Response {
```

2022-08-27 22:25 UTC, AzureMarker commented on examples/axum-spa/Cargo.toml
> +[package]
Reactivating this: The `main.rs` file should be at `examples/axum-spa/main.rs` to fit into the project layout correctly. Otherwise, this happens:
```
$ cargo check --example axum-spa
error: no example target named `axum-spa`
```

2022-08-27 22:30 UTC, AzureMarker requested changes

2022-08-27 22:30 UTC, AzureMarker commented on examples/axum-spa/src/main.rs
> +use axum::{
You'll need to register this example in the top level `Cargo.toml` file so it has the dependencies it needs:
```toml
[[example]]
name = "axum-spa"
path = "examples/axum-spa/main.rs"
required-features = ["axum-ex"]
```

2022-08-27 22:30 UTC, AzureMarker commented on examples/axum-spa/src/main.rs
> +    match Assets::get(path.as_str()) {
`path` is already a `&str`, so there's a compile time error:
```
error[E0599]: no method named `as_str` found for reference `&str` in the current scope
    --> examples/axum-spa/main.rs:33:26
     |
33   |   match Assets::get(path.as_str()) {
     |                          ^^^^^^
     |
help: remove this method call
     |
33   -   match Assets::get(path.as_str()) {
33   +   match Assets::get(path) {
     | 
```

```suggestion
    match Assets::get(path) {
```

2022-08-28 15:11 UTC, frederikhors commented on examples/axum-spa/src/main.rs
> +use axum::{
Done.

2022-08-28 15:13 UTC, frederikhors commented on examples/axum-spa/Cargo.toml
> +[package]
Done.

2022-08-28 15:15 UTC, frederikhors commented on examples/axum-spa/src/main.rs
> +    match Assets::get(path.as_str()) {
Done.

2022-08-28 15:16 UTC, frederikhors commented on examples/axum-spa/src/main.rs
> +async fn static_handler(uri: Uri) -> impl IntoResponse {
Done except for `not_found` handler because it gives the error: `expected struct `Response`, found tuple`.

Can you suggest a fix for this?

2022-08-28 15:57 UTC, pyrossh commented on examples/axum-spa/src/main.rs
> +async fn static_handler(uri: Uri) -> impl IntoResponse {
Basically instead of returning a tuple. You need to return a `Response` struct, You can look at our other axum [example](https://github.com/pyrossh/rust-embed/blob/master/examples/axum.rs),
```rust
Response::builder().status(StatusCode::NOT_FOUND).body(boxed(Full::from("404")))
```

2022-08-28 16:45 UTC, frederikhors commented on examples/axum-spa/src/main.rs
> +async fn static_handler(uri: Uri) -> impl IntoResponse {
Done! 😄

2022-08-28 17:26 UTC, AzureMarker commented on examples/axum-spa/src/main.rs
> +async fn static_handler(uri: Uri) -> impl IntoResponse {
BTW, another way of doing the 404 is `(StatusCode::NOT_FOUND, "404").into_response()`, which avoids an unwrap :)

2022-08-28 17:30 UTC, AzureMarker approved these changes

2022-08-28 18:53 UTC, AzureMarker commented on examples/axum-spa/src/main.rs
> +async fn static_handler(uri: Uri) -> impl IntoResponse {
@frederikhors I see you unresolved this. Let me know if I should wait for another commit before merging.

2022-08-28 19:02 UTC, frederikhors commented on examples/axum-spa/src/main.rs
> +async fn static_handler(uri: Uri) -> impl IntoResponse {
Nope. It's fine for me.

2022-08-28 20:43 UTC, merged