Add mime-guess feature to statically store mimetype
pyrossh/rust-embed pull request #203
Opened 2023-01-16 10:01 UTC by BBaoVanC

Closes #192 

TODO:

- it feels weird with the `&Cow<'static, str>`, not sure if I'm doing that right
- investigate whether I can do the cfg macro on an individual function arg instead of duplicating the entire `__rust_embed_new` function

2023-01-17 19:33 UTC, pyrossh commented
Hmmm wonder why the pipeline hasn't triggered but looks good though.

2023-01-17 19:37 UTC, pyrossh approved these changes

2023-01-17 19:38 UTC, pyrossh approved these changes

2023-01-17 19:40 UTC, pyrossh commented
Will try closing and opening the PR to see if the pipeline gets triggered.

2023-01-18 02:51 UTC, AzureMarker commented
The pipeline needs to be manually approved to run:
![image](https://user-images.githubusercontent.com/4417660/213070542-94f0c5b2-4b88-4050-a7ec-6d832fffd2b0.png)

2023-01-18 03:16 UTC, AzureMarker requested changes

2023-01-18 03:16 UTC, AzureMarker commented on utils/src/lib.rs
> +  pub fn mimetype(&self) -> &Cow<str> {
This can return `&str` instead

2023-01-18 03:16 UTC, AzureMarker commented on impl/src/lib.rs
> +    quote! { #mt }
You shouldn't need to run strings through `quote`

2023-01-18 03:16 UTC, AzureMarker commented on impl/src/lib.rs
> +    let mt = file.metadata.mimetype().to_string();
`to_string` shouldn't be needed

2023-01-18 03:16 UTC, AzureMarker commented on impl/src/lib.rs
> +              metadata: rust_embed::Metadata::__rust_embed_new([#(#hash),*], #last_modified, #mimetype)
If you want the parameter to be optional, this call has to be extracted

2023-01-18 04:04 UTC, BBaoVanC commented on impl/src/lib.rs
> +              metadata: rust_embed::Metadata::__rust_embed_new([#(#hash),*], #last_modified, #mimetype)
extracted as in it only gets added when the feature is enabled? I couldn't figure out how to do that

2023-01-18 04:50 UTC, AzureMarker commented on impl/src/lib.rs
> +              metadata: rust_embed::Metadata::__rust_embed_new([#(#hash),*], #last_modified, #mimetype)
i.e.
```rust
let metadata_tokens = quote! {
    rust_embed::Metadata::__rust_embed_new([#(#hash),*], #last_modified, #mimetype)
};

// ...

Some(rust_embed::EmbeddedFile {
    data: std::borrow::Cow::from(bytes),
    metadata: #metadata
})
```

2023-01-18 20:41 UTC, BBaoVanC commented on impl/src/lib.rs
> +  let mimetype = quote! { None };
Hmm somehow it did work, although I'll try and rewrite it anyways like in your other comment.

2023-01-18 23:54 UTC, BBaoVanC commented on impl/src/lib.rs
> +              metadata: rust_embed::Metadata::__rust_embed_new([#(#hash),*], #last_modified, #mimetype)
Does this look better? https://github.com/pyrossh/rust-embed/pull/203/files#diff-8230eaab64c15b319536adf4e223a85b729dd190b4c1a2095e293fdaa4e7da57

2023-01-28 22:31 UTC, AzureMarker approved these changes

2023-01-28 22:32 UTC, merged